changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - github-actions
  categories:
    - title: Security
      labels:
        - security
    - title: Breaking Changes
      labels:
        - breaking
    - title: Features
      labels:
        - feat
        - feature
        - enhancement
    - title: Bug Fixes
      labels:
        - fix
        - bug
    - title: Documentation
      labels:
        - docs
        - documentation
    - title: Performance
      labels:
        - perf
        - performance
    - title: Other Changes
      labels:
        - "*"
